spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/edu?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234qwer
  web:
    resources:
      static-locations: classpath:/front/